{
 "title": "Chaotic App Observability",
 "tags": [
  "sre",
  "chaos",
  "fastapi"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "request_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Overall Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(request_count_total[1m])", "legendFormat": "requests/sec" }
   ]
  },
  {
   "title": "Request Latency (excluding /delay)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_latency_seconds_bucket{endpoint!=\"/delay\"}[1m])) by (le)) ",
     "legendFormat": "P95 latency"
    }
   ]
  },
  {
   "title": "HTTP Status Code Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(chaotic_http_responses_total[1m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Health Check Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(chaotic_http_responses_total{status_code=\"200\"}[1m])",
     "legendFormat": "200 OK /health"
    }
   ]
  },
  {
   "title": "Chaos Traffic Rate (/unstable)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(chaos_test_requests_total[1m])",
     "legendFormat": "chaos req/sec"
    }
   ]
  },
  {
   "title": "Chaos Failures (/unstable)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(chaos_test_failures_total[1m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Artificial Delay Distribution (/delay)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(chaos_test_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "delay P95"
    }
   ]
  }
 ]
}